package dungeongine.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ItemEditorGUI {
	private JList itemList;
	private JSpinner level;
	private JTextField name;
	private JCheckBox craftable;
	private JCheckBox equippable;
	private JComboBox primary;
	private JComboBox secondary;

	public ItemEditorGUI() {
		equippable.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				primary.setEnabled(equippable.isSelected());
				secondary.setEnabled(equippable.isSelected());
			}
		});
	}

	public static void start() {
		GUI.setUI();
		new ItemEditorGUI();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		itemList = new JList();
		itemList.setSelectionMode(0);
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 2;
		gbc.weightx = 0.5;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(itemList, gbc);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.gridheight = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel1.add(panel2, gbc);
		name = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(name, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Name");
		label1.setDisplayedMnemonic('N');
		label1.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.EAST;
		gbc.insets = new Insets(3, 3, 3, 3);
		panel2.add(label1, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Level");
		label2.setDisplayedMnemonic('L');
		label2.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.EAST;
		gbc.insets = new Insets(3, 3, 3, 3);
		panel2.add(label2, gbc);
		level = new JSpinner();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 0;
		gbc.weightx = 0.2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(level, gbc);
		craftable = new JCheckBox();
		craftable.setEnabled(true);
		craftable.setSelected(false);
		craftable.setText("Craftable");
		craftable.setMnemonic('C');
		craftable.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.gridwidth = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel2.add(craftable, gbc);
		equippable = new JCheckBox();
		equippable.setText("Equippable");
		equippable.setMnemonic('E');
		equippable.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 4;
		gbc.anchor = GridBagConstraints.WEST;
		panel2.add(equippable, gbc);
		primary = new JComboBox();
		primary.setEnabled(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 5;
		gbc.gridwidth = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(primary, gbc);
		final JLabel label3 = new JLabel();
		label3.setText("Primary");
		label3.setDisplayedMnemonic('P');
		label3.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.EAST;
		gbc.insets = new Insets(3, 3, 3, 3);
		panel2.add(label3, gbc);
		secondary = new JComboBox();
		secondary.setEnabled(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 6;
		gbc.gridwidth = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel2.add(secondary, gbc);
		final JLabel label4 = new JLabel();
		label4.setText("Secondary");
		label4.setDisplayedMnemonic('S');
		label4.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.EAST;
		gbc.insets = new Insets(3, 3, 3, 3);
		panel2.add(label4, gbc);
		final JSeparator separator1 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.BOTH;
		panel2.add(separator1, gbc);
		final JSeparator separator2 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 4;
		gbc.fill = GridBagConstraints.BOTH;
		panel2.add(separator2, gbc);
		label1.setLabelFor(name);
		label2.setLabelFor(level);
		label3.setLabelFor(primary);
		label4.setLabelFor(secondary);
	}
}
